---
apiVersion: v1
kind: ConfigMap
metadata:
  name: roaseq-config
  namespace: roaseq
data:
  NODE_ENV: "production"
  PORT: "3007"
  CORS_ORIGIN: "https://roaseq.antieq.com"
  DB_HOST: "roaseq-postgres"
  DB_PORT: "5432"
  DB_NAME: "roaseq"
  DB_USER: "roaseq"
  REDIS_HOST: "roaseq-redis"
  REDIS_PORT: "6379"
