---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: roaseq-ingress
  namespace: roaseq
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - app.roaseq.com
        - roaseq.antieq.com
  rules:
    - host: app.roaseq.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: roaseq-app
                port:
                  number: 3007
    - host: roaseq.antieq.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: roaseq-app
                port:
                  number: 3007
